# namespace autocreate argo
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: will-playground
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: will-playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-playground
  template:
    metadata:
      labels:
        app: will-playground
    spec:
      containers:
      - name: will-playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: will-playground-ingres
  namespace: dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: will-playground
            port:
              number: 8888